*Chunk Jokes and https://www.alphavantage.co for stock data

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import seaborn as sns
import urllib
import json

import urllib.request
import urllib.request, urllib.parse, urllib.error

In [0]:
# chunk website
url = 'https://api.chucknorris.io/jokes/random'
user_agent = 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.7) Gecko/2009021910 Firefox/3.0.7'

#url = "http://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers"
headers={'User-Agent':user_agent,} 

request=urllib.request.Request(url,None,headers) #The assembled request
response = urllib.request.urlopen(request)
data = response.read() # The data u need

In [56]:
data

b'{"categories":[],"created_at":"2020-01-05 13:42:30.480041","icon_url":"https://assets.chucknorris.host/img/avatar/chuck-norris.png","id":"jDW-Of09QKyxFC7-2ExH3Q","updated_at":"2020-01-05 13:42:30.480041","url":"https://api.chucknorris.io/jokes/jDW-Of09QKyxFC7-2ExH3Q","value":"The time was afraid to go by fast because it didn\'t wanna be ahead of Chuck Norris."}'

In [0]:
data = json.loads( data)

In [58]:
data

{'categories': [],
 'created_at': '2020-01-05 13:42:30.480041',
 'icon_url': 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
 'id': 'jDW-Of09QKyxFC7-2ExH3Q',
 'updated_at': '2020-01-05 13:42:30.480041',
 'url': 'https://api.chucknorris.io/jokes/jDW-Of09QKyxFC7-2ExH3Q',
 'value': "The time was afraid to go by fast because it didn't wanna be ahead of Chuck Norris."}

In [0]:
# get category
url = 'https://api.chucknorris.io/jokes/categories'

In [0]:
def getdata(url):
  user_agent = 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.7) Gecko/2009021910 Firefox/3.0.7'

  #url = "http://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers"
  headers={'User-Agent':user_agent,} 

  request=urllib.request.Request(url,None,headers) #The assembled request
  response = urllib.request.urlopen(request)
  data = response.read() # The data u need
  data = json.loads(data)
  return data

In [0]:
categories = getdata(url)

In [66]:
categories

['animal',
 'career',
 'celebrity',
 'dev',
 'explicit',
 'fashion',
 'food',
 'history',
 'money',
 'movie',
 'music',
 'political',
 'religion',
 'science',
 'sport',
 'travel']

In [76]:
!pip install alpha_vantage

Collecting alpha_vantage
  Downloading https://files.pythonhosted.org/packages/12/e3/72ec32d859a363c2eebaa42e0d4abb5ac7172a7a77a2307576ceb5fc1b42/alpha_vantage-2.2.0.tar.gz
Collecting aiohttp
  Downloading https://files.pythonhosted.org/packages/7c/39/7eb5f98d24904e0f6d3edb505d4aa60e3ef83c0a58d6fe18244a51757247/aiohttp-3.6.2-cp36-cp36m-manylinux1_x86_64.whl (1.2MB)
     |████████████████████████████████| 1.2MB 4.0MB/s
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from alpha_vantage) (2.23.0)
Requirement already satisfied: typing-extensions>=3.6.5; python_version < "3.7" in /usr/local/lib/python3.6/dist-packages (from aiohttp->alpha_vantage) (3.6.6)
Collecting async-timeout<4.0,>=3.0
  Downloading https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.6/dist-packages (from aiohttp->alpha_vantage) (19.3.0)
Collecting idna-ssl>=1.0; python_version < "3.7"
  Downloading https://files.pythonhosted.org/packages/46/03/07c4894aae38b0de52b52586b24bf189bb83e4ddabfe2e2c8f2419eec6f4/idna-ssl-1.1.0.tar.gz
Collecting yarl<2.0,>=1.0
  Downloading https://files.pythonhosted.org/packages/95/8f/0209fc5d975f839344c33c822ff2f7ef80f6b1e984673a5a68f960bfa583/yarl-1.4.2-cp36-cp36m-manylinux1_x86_64.whl (252kB)
     |████████████████████████████████| 256kB 12.8MB/s
Requirement already satisfied: chardet<4.0,>=2.0 in /usr/local/lib/python3.6/dist-packages (from aiohttp->alpha_vantage) (3.0.4)
Collecting multidict<5.0,>=4.5
  Downloading https://files.pythonhosted.org/packages/1a/95/f50352b5366e7d579e8b99631680a9e32e1b22adfa1629a8f23b1d22d5e2/multidict-4.7.6-cp36-cp36m-manylinux1_x86_64.whl (148kB)
     |████████████████████████████████| 153kB 15.5MB/s
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->alpha_vantage) (2.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->alpha_vantage) (2020.4.5.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->alpha_vantage) (1.24.3)
Building wheels for collected packages: alpha-vantage, idna-ssl
  Building wheel for alpha-vantage (setup.py) ... done
  Created wheel for alpha-vantage: filename=alpha_vantage-2.2.0-cp36-none-any.whl size=25705 sha256=4ec4454b8b6741ef17c7a348a266530a858ed5d75b8ee7d9efe99f08e31f8ea1
  Stored in directory: /root/.cache/pip/wheels/3a/fa/05/80b0afcbd2a4de8bd2a0c5cd77084e3d3a9cc12c48be9b7f84
  Building wheel for idna-ssl (setup.py) ... done
  Created wheel for idna-ssl: filename=idna_ssl-1.1.0-cp36-none-any.whl size=3162 sha256=f56f2a5564d59401e86cf52803254ea0cc71d07c328b38da7c0836804181bd2a
  Stored in directory: /root/.cache/pip/wheels/d3/00/b3/32d613e19e08a739751dd6bf998cfed277728f8b2127ad4eb7
Successfully built alpha-vantage idna-ssl
Installing collected packages: async-timeout, idna-ssl, multidict, yarl, aiohttp, alpha-vantage
Successfully installed aiohttp-3.6.2 alpha-vantage-2.2.0 async-timeout-3.0.1 idna-ssl-1.1.0 multidict-4.7.6 yarl-1.4.2

In [0]:
from alpha_vantage.timeseries import TimeSeries
import json
# Your key here
key = 'XXXXXXXXXXXXXX'

def getdata(ticker):
  #user_agent = 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.7) Gecko/2009021910 Firefox/3.0.7'

  ts = TimeSeries(key)
  stock, meta = ts.get_daily(symbol=ticker)
  print(stock)
  stock = pd.DataFrame.from_dict(stock)
  print(stock)
  return stock

In [87]:
getdata('goog')

{'2020-05-19': {'1. open': '1387.0000', '2. high': '1392.0000', '3. low': '1373.4800', '4. close': '1373.4800', '5. volume': '1271509'}, '2020-05-18': {'1. open': '1361.7500', '2. high': '1392.3300', '3. low': '1354.2500', '4. close': '1383.9400', '5. volume': '1823964'}, '2020-05-15': {'1. open': '1350.0000', '2. high': '1374.4800', '3. low': '1339.0000', '4. close': '1373.1900', '5. volume': '1707747'}, '2020-05-14': {'1. open': '1335.0200', '2. high': '1357.4200', '3. low': '1323.9100', '4. close': '1356.1300', '5. volume': '1603077'}, '2020-05-13': {'1. open': '1377.0500', '2. high': '1385.4800', '3. low': '1328.4000', '4. close': '1349.3300', '5. volume': '1812585'}, '2020-05-12': {'1. open': '1407.1200', '2. high': '1415.0000', '3. low': '1374.7700', '4. close': '1375.7400', '5. volume': '1390600'}, '2020-05-11': {'1. open': '1378.2800', '2. high': '1416.5300', '3. low': '1377.1500', '4. close': '1403.2600', '5. volume': '1412116'}, '2020-05-08': {'1. open': '1383.1300', '2. high': '1398.7600', '3. low': '1375.4800', '4. close': '1388.3700', '5. volume': '1388068'}, '2020-05-07': {'1. open': '1365.9400', '2. high': '1377.6000', '3. low': '1355.2700', '4. close': '1372.5600', '5. volume': '1399759'}, '2020-05-06': {'1. open': '1361.6900', '2. high': '1371.1200', '3. low': '1347.2900', '4. close': '1347.3000', '5. volume': '1215423'}, '2020-05-05': {'1. open': '1337.9200', '2. high': '1373.9400', '3. low': '1337.4600', '4. close': '1351.1100', '5. volume': '1651533'}, '2020-05-04': {'1. open': '1308.2300', '2. high': '1327.6600', '3. low': '1299.0000', '4. close': '1326.8000', '5. volume': '1504017'}, '2020-05-01': {'1. open': '1328.5000', '2. high': '1352.0700', '3. low': '1311.0000', '4. close': '1320.6100', '5. volume': '2072639'}, '2020-04-30': {'1. open': '1324.8800', '2. high': '1352.8200', '3. low': '1322.4900', '4. close': '1348.6600', '5. volume': '2668906'}, '2020-04-29': {'1. open': '1341.4600', '2. high': '1359.9900', '3. low': '1325.3400', '4. close': '1341.4800', '5. volume': '3793630'}, '2020-04-28': {'1. open': '1287.9300', '2. high': '1288.0500', '3. low': '1232.2000', '4. close': '1233.6700', '5. volume': '2951309'}, '2020-04-27': {'1. open': '1296.0000', '2. high': '1296.1500', '3. low': '1269.0000', '4. close': '1275.8800', '5. volume': '1600563'}, '2020-04-24': {'1. open': '1261.1700', '2. high': '1280.4000', '3. low': '1249.4500', '4. close': '1279.3100', '5. volume': '1640394'}, '2020-04-23': {'1. open': '1271.5500', '2. high': '1293.3100', '3. low': '1265.6700', '4. close': '1276.3100', '5. volume': '1566203'}, '2020-04-22': {'1. open': '1245.5400', '2. high': '1285.6100', '3. low': '1242.0000', '4. close': '1263.2100', '5. volume': '2093140'}, '2020-04-21': {'1. open': '1247.0000', '2. high': '1254.2700', '3. low': '1209.7100', '4. close': '1216.3400', '5. volume': '2153003'}, '2020-04-20': {'1. open': '1271.0000', '2. high': '1281.6000', '3. low': '1261.3700', '4. close': '1266.6100', '5. volume': '1695488'}, '2020-04-17': {'1. open': '1284.8500', '2. high': '1294.4300', '3. low': '1271.2300', '4. close': '1283.2500', '5. volume': '1949042'}, '2020-04-16': {'1. open': '1274.1000', '2. high': '1279.0000', '3. low': '1242.6200', '4. close': '1263.4700', '5. volume': '2518099'}, '2020-04-15': {'1. open': '1245.6100', '2. high': '1280.4600', '3. low': '1240.4000', '4. close': '1262.4700', '5. volume': '1671703'}, '2020-04-14': {'1. open': '1245.0900', '2. high': '1282.0700', '3. low': '1236.9300', '4. close': '1269.2300', '5. volume': '2470353'}, '2020-04-13': {'1. open': '1209.1800', '2. high': '1220.5100', '3. low': '1187.6000', '4. close': '1217.5600', '5. volume': '1739828'}, '2020-04-09': {'1. open': '1224.0800', '2. high': '1225.5700', '3. low': '1196.7400', '4. close': '1211.4500', '5. volume': '2175421'}, '2020-04-08': {'1. open': '1206.5000', '2. high': '1219.0700', '3. low': '1188.1600', '4. close': '1210.2800', '5. volume': '1975135'}, '2020-04-07': {'1. open': '1221.0000', '2. high': '1225.0000', '3. low': '1182.2300', '4. close': '1186.5100', '5. volume': '2387329'}, '2020-04-06': {'1. open': '1138.0000', '2. high': '1194.6600', '3. low': '1130.9400', '4. close': '1186.9200', '5. volume': '2664723'}, '2020-04-03': {'1. open': '1119.0200', '2. high': '1123.5400', '3. low': '1079.8100', '4. close': '1097.8800', '5. volume': '2313400'}, '2020-04-02': {'1. open': '1098.2600', '2. high': '1126.8600', '3. low': '1096.4000', '4. close': '1120.8400', '5. volume': '1964881'}, '2020-04-01': {'1. open': '1122.0000', '2. high': '1129.6900', '3. low': '1097.4500', '4. close': '1105.6200', '5. volume': '2344173'}, '2020-03-31': {'1. open': '1147.3000', '2. high': '1175.3100', '3. low': '1138.1400', '4. close': '1162.8100', '5. volume': '2487983'}, '2020-03-30': {'1. open': '1125.0400', '2. high': '1151.6300', '3. low': '1096.4800', '4. close': '1146.8200', '5. volume': '2574061'}, '2020-03-27': {'1. open': '1125.6700', '2. high': '1150.6700', '3. low': '1105.9100', '4. close': '1110.7100', '5. volume': '3208495'}, '2020-03-26': {'1. open': '1111.8000', '2. high': '1169.9700', '3. low': '1093.5300', '4. close': '1161.7500', '5. volume': '3573755'}, '2020-03-25': {'1. open': '1126.4700', '2. high': '1148.9000', '3. low': '1086.0100', '4. close': '1102.4900', '5. volume': '4081528'}, '2020-03-24': {'1. open': '1103.7700', '2. high': '1135.0000', '3. low': '1090.6200', '4. close': '1134.4600', '5. volume': '3344450'}, '2020-03-23': {'1. open': '1061.3200', '2. high': '1071.3200', '3. low': '1013.5400', '4. close': '1056.6200', '5. volume': '4044137'}, '2020-03-20': {'1. open': '1135.7200', '2. high': '1143.9900', '3. low': '1065.4900', '4. close': '1072.3200', '5. volume': '3601750'}, '2020-03-19': {'1. open': '1093.0500', '2. high': '1157.9700', '3. low': '1060.1100', '4. close': '1115.2900', '5. volume': '3651106'}, '2020-03-18': {'1. open': '1056.5100', '2. high': '1106.5000', '3. low': '1037.2800', '4. close': '1096.8000', '5. volume': '4233435'}, '2020-03-17': {'1. open': '1093.1100', '2. high': '1130.8600', '3. low': '1056.0100', '4. close': '1119.8000', '5. volume': '3861489'}, '2020-03-16': {'1. open': '1096.0000', '2. high': '1152.2700', '3. low': '1074.4400', '4. close': '1084.3300', '5. volume': '4252365'}, '2020-03-13': {'1. open': '1179.0000', '2. high': '1219.7600', '3. low': '1117.1400', '4. close': '1219.7300', '5. volume': '3700125'}, '2020-03-12': {'1. open': '1126.0000', '2. high': '1193.8700', '3. low': '1113.3000', '4. close': '1114.9100', '5. volume': '4226748'}, '2020-03-11': {'1. open': '1249.7000', '2. high': '1260.9600', '3. low': '1196.0700', '4. close': '1215.4100', '5. volume': '2611229'}, '2020-03-10': {'1. open': '1260.0000', '2. high': '1281.1500', '3. low': '1218.7700', '4. close': '1280.3900', '5. volume': '2611373'}, '2020-03-09': {'1. open': '1205.3000', '2. high': '1254.7600', '3. low': '1200.0000', '4. close': '1215.5600', '5. volume': '3365365'}, '2020-03-06': {'1. open': '1277.0600', '2. high': '1306.2200', '3. low': '1261.0500', '4. close': '1298.4100', '5. volume': '2660628'}, '2020-03-05': {'1. open': '1350.2000', '2. high': '1358.9100', '3. low': '1305.1000', '4. close': '1319.0400', '5. volume': '2561288'}, '2020-03-04': {'1. open': '1359.2300', '2. high': '1388.0900', '3. low': '1343.1100', '4. close': '1386.5200', '5. volume': '1913315'}, '2020-03-03': {'1. open': '1399.4200', '2. high': '1410.1500', '3. low': '1332.0000', '4. close': '1341.3900', '5. volume': '2402326'}, '2020-03-02': {'1. open': '1351.6100', '2. high': '1390.8700', '3. low': '1326.8200', '4. close': '1389.1100', '5. volume': '2431468'}, '2020-02-28': {'1. open': '1277.5000', '2. high': '1341.1400', '3. low': '1271.0000', '4. close': '1339.3300', '5. volume': '3790618'}, '2020-02-27': {'1. open': '1362.0600', '2. high': '1371.7000', '3. low': '1317.1700', '4. close': '1318.0900', '5. volume': '2978300'}, '2020-02-26': {'1. open': '1396.1400', '2. high': '1415.7000', '3. low': '1379.0000', '4. close': '1393.1800', '5. volume': '2204037'}, '2020-02-25': {'1. open': '1433.0000', '2. high': '1438.1400', '3. low': '1382.4000', '4. close': '1388.4500', '5. volume': '2478278'}, '2020-02-24': {'1. open': '1426.1100', '2. high': '1436.9700', '3. low': '1411.3900', '4. close': '1421.5900', '5. volume': '2867053'}, '2020-02-21': {'1. open': '1508.0300', '2. high': '1512.2100', '3. low': '1480.4400', '4. close': '1485.1100', '5. volume': '1732273'}, '2020-02-20': {'1. open': '1522.0000', '2. high': '1529.6400', '3. low': '1506.8200', '4. close': '1518.1500', '5. volume': '1096552'}, '2020-02-19': {'1. open': '1525.0700', '2. high': '1532.1100', '3. low': '1521.4000', '4. close': '1526.6900', '5. volume': '949268'}, '2020-02-18': {'1. open': '1515.0000', '2. high': '1531.6300', '3. low': '1512.5900', '4. close': '1519.6700', '5. volume': '1121140'}, '2020-02-14': {'1. open': '1515.6000', '2. high': '1520.7400', '3. low': '1507.3400', '4. close': '1520.7400', '5. volume': '1197836'}, '2020-02-13': {'1. open': '1512.6900', '2. high': '1527.1800', '3. low': '1504.6000', '4. close': '1514.6600', '5. volume': '929730'}, '2020-02-12': {'1. open': '1514.4800', '2. high': '1520.6900', '3. low': '1508.1100', '4. close': '1518.2700', '5. volume': '1167565'}, '2020-02-11': {'1. open': '1511.8100', '2. high': '1529.6300', '3. low': '1505.6400', '4. close': '1508.7900', '5. volume': '1344633'}, '2020-02-10': {'1. open': '1474.3200', '2. high': '1509.5000', '3. low': '1474.3200', '4. close': '1508.6800', '5. volume': '1419876'}, '2020-02-07': {'1. open': '1467.3000', '2. high': '1485.8400', '3. low': '1466.3500', '4. close': '1479.2300', '5. volume': '1172270'}, '2020-02-06': {'1. open': '1450.3300', '2. high': '1482.0000', '3. low': '1449.5700', '4. close': '1476.2300', '5. volume': '1679384'}, '2020-02-05': {'1. open': '1462.4200', '2. high': '1463.8400', '3. low': '1430.5600', '4. close': '1448.2300', '5. volume': '1986157'}, '2020-02-04': {'1. open': '1457.0700', '2. high': '1469.5000', '3. low': '1426.3000', '4. close': '1447.0700', '5. volume': '3932954'}, '2020-02-03': {'1. open': '1462.0000', '2. high': '1490.0000', '3. low': '1458.9900', '4. close': '1485.9400', '5. volume': '3055216'}, '2020-01-31': {'1. open': '1468.9000', '2. high': '1470.1300', '3. low': '1428.5300', '4. close': '1434.2300', '5. volume': '2417214'}, '2020-01-30': {'1. open': '1439.9600', '2. high': '1457.2800', '3. low': '1436.4000', '4. close': '1455.8400', '5. volume': '1339421'}, '2020-01-29': {'1. open': '1458.8000', '2. high': '1465.4300', '3. low': '1446.7400', '4. close': '1458.6300', '5. volume': '1078667'}, '2020-01-28': {'1. open': '1443.0000', '2. high': '1456.0000', '3. low': '1432.4700', '4. close': '1452.5600', '5. volume': '1577422'}, '2020-01-27': {'1. open': '1431.0000', '2. high': '1438.0700', '3. low': '1421.2000', '4. close': '1433.9000', '5. volume': '1755201'}, '2020-01-24': {'1. open': '1493.5900', '2. high': '1495.4900', '3. low': '1465.2500', '4. close': '1466.7100', '5. volume': '1784644'}, '2020-01-23': {'1. open': '1487.6400', '2. high': '1495.5200', '3. low': '1482.1000', '4. close': '1486.6500', '5. volume': '1351354'}, '2020-01-22': {'1. open': '1491.0000', '2. high': '1503.2100', '3. low': '1484.9300', '4. close': '1485.9500', '5. volume': '1610846'}, '2020-01-21': {'1. open': '1479.1200', '2. high': '1491.8500', '3. low': '1471.2000', '4. close': '1484.4000', '5. volume': '2008830'}, '2020-01-17': {'1. open': '1462.9100', '2. high': '1481.3000', '3. low': '1458.2200', '4. close': '1480.3900', '5. volume': '2396215'}, '2020-01-16': {'1. open': '1447.4400', '2. high': '1451.9900', '3. low': '1440.9200', '4. close': '1451.7000', '5. volume': '1173688'}, '2020-01-15': {'1. open': '1430.2100', '2. high': '1441.3900', '3. low': '1430.2100', '4. close': '1439.2000', '5. volume': '1282685'}, '2020-01-14': {'1. open': '1439.0100', '2. high': '1441.8000', '3. low': '1428.3700', '4. close': '1430.8800', '5. volume': '1560453'}, '2020-01-13': {'1. open': '1436.1300', '2. high': '1440.5200', '3. low': '1426.0200', '4. close': '1439.2300', '5. volume': '1378286'}, '2020-01-10': {'1. open': '1427.5600', '2. high': '1434.9300', '3. low': '1418.3500', '4. close': '1429.7300', '5. volume': '1821566'}, '2020-01-09': {'1. open': '1420.5700', '2. high': '1427.3300', '3. low': '1410.2700', '4. close': '1419.8300', '5. volume': '1502664'}, '2020-01-08': {'1. open': '1392.0800', '2. high': '1411.5800', '3. low': '1390.8400', '4. close': '1404.3200', '5. volume': '1529177'}, '2020-01-07': {'1. open': '1397.9400', '2. high': '1402.9900', '3. low': '1390.3800', '4. close': '1393.3400', '5. volume': '1511693'}, '2020-01-06': {'1. open': '1350.0000', '2. high': '1396.5000', '3. low': '1350.0000', '4. close': '1394.2100', '5. volume': '1733149'}, '2020-01-03': {'1. open': '1347.8600', '2. high': '1372.5000', '3. low': '1345.5400', '4. close': '1360.6600', '5. volume': '1187006'}, '2020-01-02': {'1. open': '1341.5500', '2. high': '1368.1400', '3. low': '1341.5500', '4. close': '1367.3700', '5. volume': '1406731'}, '2019-12-31': {'1. open': '1330.1100', '2. high': '1338.0000', '3. low': '1329.0900', '4. close': '1337.0200', '5. volume': '962468'}, '2019-12-30': {'1. open': '1350.0000', '2. high': '1353.0000', '3. low': '1334.0200', '4. close': '1336.1400', '5. volume': '1051323'}, '2019-12-27': {'1. open': '1362.9900', '2. high': '1364.5300', '3. low': '1349.3100', '4. close': '1351.8900', '5. volume': '1038718'}, '2019-12-26': {'1. open': '1346.1700', '2. high': '1361.3300', '3. low': '1344.4700', '4. close': '1360.4000', '5. volume': '667754'}}
          2020-05-19 2020-05-18 2020-05-15  ... 2019-12-30 2019-12-27 2019-12-26
1. open    1387.0000  1361.7500  1350.0000  ...  1350.0000  1362.9900  1346.1700
2. high    1392.0000  1392.3300  1374.4800  ...  1353.0000  1364.5300  1361.3300
3. low     1373.4800  1354.2500  1339.0000  ...  1334.0200  1349.3100  1344.4700
4. close   1373.4800  1383.9400  1373.1900  ...  1336.1400  1351.8900  1360.4000
5. volume    1271509    1823964    1707747  ...    1051323    1038718     667754

[5 rows x 100 columns]

          2020-05-19 2020-05-18 2020-05-15  ... 2019-12-30 2019-12-27 2019-12-26
1. open    1387.0000  1361.7500  1350.0000  ...  1350.0000  1362.9900  1346.1700
2. high    1392.0000  1392.3300  1374.4800  ...  1353.0000  1364.5300  1361.3300
3. low     1373.4800  1354.2500  1339.0000  ...  1334.0200  1349.3100  1344.4700
4. close   1373.4800  1383.9400  1373.1900  ...  1336.1400  1351.8900  1360.4000
5. volume    1271509    1823964    1707747  ...    1051323    1038718     667754

[5 rows x 100 columns]